custom_tos_enabled:
  default: true
  type: bool

tos_content_fr:
  default: "<p>Conditions d'utilisation en français ici</p>"
  type: string
  textarea: true

tos_content_en:
  default: "<p>Terms of Service in English here</p>"
  type: string
  textarea: true